version: '2'
services:
  sensors_linux_x64:
    image: "mklimuk/gobuild:1.23-cross-buster"
    volumes:
      - .:/src/sensors
      - $GOPATH/pkg/mod/cache/download:/go/pkg/mod/cache/download
    command: sh -c "cd /src/sensors && make clean && make compile"
